Add copy/cut/paste to context menu
nick-keller/react-datasheet-grid pull request #247
Opened 2023-01-29 18:34 UTC by alpharaoh

Handles cases where it's not supported/insufficient permissions in the browser; there will be an alert popup, similar to how google meets behaves (try to use "paste" in google meets in firefox)

2023-01-29 19:10 UTC, alpharaoh commented on package.json
> +    "typescript": "^4.9.4"
Needed updating to access the `ClipboardItem` class

2023-01-31 09:29 UTC, nick-keller requested changes

2023-01-31 09:29 UTC, nick-keller commented on src/components/DataSheetGrid.tsx
> +      }, [selection, activeCell, deleteRows, duplicateRows, insertRowAfter])
Aren't you missing `applyPasteDataToDatasheet`?

2023-02-01 12:34 UTC, nick-keller approved these changes

2023-02-01 12:35 UTC, merged