Fixed an error when ctrl+v(cmd+v) didn't work during editing mode.
nick-keller/react-datasheet-grid pull request #258
Opened 2023-02-14 12:53 UTC by devourer3

Fixed an error where ctrl+v (cmd+v) did not work during editing mode
cf) Is there a reason why preventDefaultEvent exists at that location?

2023-02-14 15:58 UTC, nick-keller requested changes

2023-02-14 20:44 UTC, devourer3 commented on src/components/DataSheetGrid.tsx
> -            event.preventDefault()
Thank you for your comment!

2023-02-15 03:50 UTC, closed without merging

2023-02-15 11:12 UTC, nick-keller commented on src/components/DataSheetGrid.tsx
> -            event.preventDefault()
Try 4.10.3

2023-02-15 11:29 UTC, devourer3 commented on src/components/DataSheetGrid.tsx
> -            event.preventDefault()
it works! thx!